config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'sessions#new'
  
    resources :users, only: [:new, :create]
  
    resource :session, only: [:new, :create, :destroy]
  
    resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :user

    validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
    PASSWORD_LENGTH = (6..25)
    USERNAME_LENGTH = (5..15)

    has_many :contacts, dependent: :delete_all

    validates_presence_of :username
    validates :name, presence: true
    validates :username, length: USERNAME_LENGTH, uniqueness: true
    validates :password, length: PASSWORD_LENGTH, allow_nil: true
    validates :email, confirmation: true,
    presence: true,
    uniqueness: true,
    format: {
      with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/,
      message: "Thats not an email!"
    },
    length: {
      minimum: 5
    }
    validates :email_confirmation, presence: true, if: :email_confirmation_required?
    
    

    attr_reader :password, :email_confirmation

    def self.find_from_credentials(username, password)
        user = find_by(username: username)
        return nil unless user
        user if user.is_password?(password)
    end

    def is_password?(password_attempt)
        BCrypt::Password.new(password_digest).is_password?(password_attempt)
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def email_confirmation_required?
        new_record? || email_confirmation.present?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def sign_in(user)
    session[:session_token] = SecureRandom.urlsafe_base64
    user.update!(session_token: session[:session_token])
  end

  def sign_out
    return unless current_user
    current_user.update!(session_token: nil)
    session.delete(:session_token)
  end

  def current_user
    @current_user ||= find_current_user
  end

  def find_current_user
    session_token = session[:session_token]
    session_token && User.find_by(session_token: session_token)
  end

  def ensure_signed_in
    return if current_user
    flash[:error] = 'you must be signed in to see this'
    redirect_to :root
  end

  def ensure_signed_out
    return unless current_user
    flash[:error] = 'you are already signed in'
    redirect_to users_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :ensure_signed_in
  before_action :load_contact, only: [:show, :edit, :update, :destroy]

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(create_params)
    @contact.user = current_user

    if @contact.save
      flash[:notice] = 'Contact created!'
      redirect_to contact_path(@contact)
    else
      flash[:error] = @contact.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit; end

  def update
    if @contact.update(update_params)
      flash[:notice] = 'Contact updated!'
      redirect_to contact_path(@contact)
    else
      flash[:error] = @contact.errors.full_messages.join(', ')
      render :edit
    end
  end

  def index
    @contacts = current_user.contacts
  end

  def show; end

  def destroy
    @contact.destroy!

    flash[:notice] = "#{@contact.name} deleted!"
    redirect_to contacts_path
  end

  private

  def create_params
    params.require(:contact).permit(:name, :company, :department, :title, :email, :phone, :description)
  end

  def update_params
    params.require(:contact).permit(:name, :company, :department, :title, :email, :phone, :description)
  end

  def load_contact
    @contact = current_user.contacts.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :ensure_signed_out, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    username = user_params[:username]
    password = user_params[:password]

    user = User.find_from_credentials(username, password)

    if user
      sign_in(user)
      flash[:notice] = "Hi, #{username}! You signed in!"
      redirect_to contacts_path
    else
      sign_in(user)
      flash[:error] = 'User not found'
      @user = User.new(username: username)
      render :new
    end
  end

  def destroy
    sign_out
    flash[:notice] = 'You signed out!'
    redirect_to new_session_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_signed_out, only: [:new, :create]
  # before_action :ensure_signed_in, only: [:show, :index]

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_params)

    if @user.save
      sign_in(@user)
      flash[:notice] = 'Congrats! You are signed in!'
      redirect_to users_path
    else
      flash[:error] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  # def index
  #   @users = User.all
  # end

  # def show
  #   @user = User.find(params[:id])
  # end

  private

  def create_params
    params.require(:user).permit(:username, :password, :name, :password, :email, :email_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/edit.html.erb
<h1 class="page-title">Edit Contact</h1>
<%= render "partials/contact_form", {contact: @contact} %>

app/views/contacts/index.html.erb
<h1 class="page-title">Contacts</h1>
<div class="contact-list">
  <% if @contacts.empty? %>
    No contacts yet :(

  <% else %>
    <% @contacts.each do |contact| %>
      <div class="contact-info">
        <h2 class="contact-title">
          <%= link_to contact.name, contact_path(contact) %>
        </h2>
        <p><%= contact.description %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/contacts/new.html.erb
<h1 class="page-title">Add a Contact</h1>
<%= render "partials/contact_form", {contact: @contact} %>

app/views/contacts/show.html.erb
<h1 class="page-title"><%= @contact.name %></h1>
<div class="show">
    <div class="contact-info info">
        <h2 class="card-title"><%= @contact.company %></h2>
        <h4><%= @contact.title %></h4>
        <h4><%= @contact.department %></h4>
        <p>Phone: <%= @contact.phone %></p>
        <p>Email: <%= @contact.email %></p>
        <p>Description: <%= @contact.description %></p>
        <div class="card-footer">
            <div class="footer-buttons">
                <%= link_to("✎", edit_contact_path(@contact), :class => "pop-button") %>
                <%= button_to("✕", @contact, method: :delete, :class=>"pop-button") %>
                <%= link_to 'Cancel', :back %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BusinessCardSaver</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <h1>Business Card Saver</h1>
      <nav>
        <% if current_user %>
          Welcome <%= current_user.username %>
          <%= button_to 'Log out', session_path, method: :delete %>
        <% end %>
        <%= link_to 'Contacts', contacts_path %>
        |
        <%= link_to 'Add Contact', new_contact_path %>
      </nav>
      <% if flash[:notice].present? %>
        <div class="notice">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:error].present? %>
        <div class="errors">
          <b>Errors:</b>

          <%= flash[:error] %>
        </div>
      <% end %>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_contact_form.html.erb
<%= form_for(contact, :html => {:class => "form"}) do |f| %>
  <div class="input-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="input-group">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class="input-group">
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  </div>
   <div class="input-group">
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>
  <div class="input-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="input-group">
    <%= f.label :department %>
    <%= f.text_field :department %>
  </div>
  <div class="input-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <%= f.submit %>
<% end %>
<%= link_to 'Back', :back %>

app/views/users/new.html.erb
<h1>Create an Account</h1>

<%= form_for @user do |form| %>
  <%= form.text_field :name,
      placeholder: 'name',
      required: true
  %>
  <%= form.email_field :email,
      placeholder: 'email',
      required: true   
  %>

  <%= form.email_field :email_confirmation, 
      placeholder: 'confirm email',
      :value => @user.email 
  %>

  <%= form.text_field :username,
      placeholder: 'Username',
      required: true,
      minlength: User::USERNAME_LENGTH.begin,
      maxlength: User::USERNAME_LENGTH.end
  %>

  <%= form.password_field :password,
      placeholder: 'password',
      required: true,
      minlength: User::PASSWORD_LENGTH.begin,
      maxlength: User::PASSWORD_LENGTH.end
  %>

  <%= submit_tag 'Create Account!' %>
<% end %>

<br>
Returning user? <%= link_to 'Sign in', new_session_path %>